apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: local-

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app
  spec:
    template:
      spec:
        containers:
        - name: app
          image: gcp-app:dev
          env:
          - name: NODE_ENV
            value: "development"
          - name: CUSTOMER_ID
            value: "local-dev"

secretGenerator:
- name: app-secrets
  literals:
  - APP_CONFIG=local-development-config
  - DATABASE_URL=sqlite://local.db

configMapGenerator:
- name: app-config
  literals:
  - customer-id=local-dev
  - environment=development
  - log-level=debug
